language: node_js

node_js:
  - "stable"

notifications:
  email: false

script:
  npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
